### ISSUE TITLE
bypass hardware method ipad 2,3,4air mini  3g gsm only and tested 

### ISSUE THREAD

**Issue by ghost** [carcabot/iCloud-Bypass#10]
this metod is not mine only test by doing and with try and error will comment with the best way and all credits goes to the person who found it and if helped please donate to the person 
many tanks

**Comment by ghost** [comment]
the process is simple need to find the correct resistor r1205 r1204 etc that will be explained in the photos the ones that actually works will be posted with all the way to do it right starting with ipad mini 3g A1455 that actually was made by me and works ok lets start

**Comment by dekepetz** [comment]
on http://pasha4ur.org.ua/articles/difdevices/131-how-unlock-apple-ipad-2-3g-icloud-locked
this mean bypass by hardware method...? is it all service on iDevice will be work or not..?

**Comment by ghost** [comment]
ipad A1455 3g  
tools
hotair station hotair gun do not use hairdryer 
small bits of plastic to wedge betewen the touch 
2 small pry open tool (can get it from ebay )
pencil sharpened 
magnify lens
and a lot of patience not mess things, google,youtube is the best tools to open the ipad 
ok lets start 
![ipad mini](https://cloud.githubusercontent.com/assets/8893985/4556147/0947f640-4ec6-11e4-9358-6e64834532d6.jpg)
the ipad mini A1455 doesnt got r1205 
the r1204 is on the left side of the a5 chip and the r1205 is on the top its hidden under cover of metall no need to take the logic board  out
ok figured out the location time to remove the r1204 with air station or soldering iron 5w with a very small tip 
ok the r1205 doesnt exist its blank space use the pencil very sharp and draw a line betewen the gaps
![pencil](https://cloud.githubusercontent.com/assets/8893985/4556287/70c391fc-4ec7-11e4-8baf-27c2cf5ab723.jpg)
ok all done now before close the ipad test it with itunes restore it if all goes good itune welcomes u with a new wifi ipad that can be registed with ur icloud account.
if goes bad it comes up as a apple tv not the worrie go back to that blank space and givi it another go with a pencil 
![ipadmini new](https://cloud.githubusercontent.com/assets/8893985/4606864/33c2c938-5234-11e4-9da9-3d60e60963ba.jpg)

**Comment by ghost** [comment]
a got the go now later will post other models and solutions

**Comment by ghost** [comment]
hi dek yes all working fine apart from the gsm of course

**Comment by ghost** [comment]
iphone 4 imei change 
http://www.youtube.com/watch?v=ZNReTW1McUU

**Comment by ghost** [comment]
another solution 
http://doulci-lover.blogspot.pt/2014/07/unlock-apple-id-and-carrier-lock-for.html

**Comment by ghost** [comment]
ipad 4 confirmed no bluetooth no gsm icloud gone ;) 
take the R1204 andR1205 
![ipad 4](https://cloud.githubusercontent.com/assets/8893985/4557240/52a958f0-4ed1-11e4-80c1-e11cbb939db3.jpg)

**Comment by trapcode** [comment]
anyone confirmed this imod solution work?

**Comment by ghost** [comment]
too soon trap but my sources are 100% correct especial the ipad mini a1455 that i didt my self :)

**Comment by trapcode** [comment]
i have no ipad for tryout, but i guess there must be a "hole" for iphones.. nothing is perfect in this world

**Comment by ghost** [comment]
"This Method Working In 100% And Can ByPass Any iPad With 3G. Why Only 3G iPads? Because After Cut The Resistor Your Damage Your iDevice Modem,And After Flash Via iTunes Your Device Will Be Activated Via Serial Number."

**Comment by ghost** [comment]
ipad 2 3g model A1396 working test solution wifi bluetooth working no gsm or icloud 
![ipad2 gsm](https://cloud.githubusercontent.com/assets/8893985/4557579/27b70008-4ed5-11e4-9a8d-5e62360349bc.jpg)

**Comment by ghost** [comment]
very importatnt to chek ur ipad model correct and the location of the resistor take ur time on this one dont rush :)

**Comment by R0of** [comment]
this is made by pasha russian!

**Comment by ghost** [comment]
yes and backup with a big forum as well :)
that actualy working and giving working solutions

**Comment by Apfelnerd** [comment]
Yes its work! but i dont do that...

**Comment by ghost** [comment]
this can be done by a technician as long u take the schematics and the info to him 
lol dam lazy tech is charging to do it well he needs to eat :)

**Comment by ghost** [comment]
hope this dont get patched by maçã :)

**Comment by ghost** [comment]
beware thet model A1455 there is one that is A1455 MM on that one u dont find any resistor its blank both just disconect the battery from the device and short r1205 using a pencil or solder

**Comment by fodil123** [comment]
Hi @danocas :)
i'm so intrested about this method, i'm an electronique technicien too, & i have all the tools needed :)
the good thig here is that resistor don't have polarity , even beginner can remove or short pins without any risk using small scope, about me i have iPad 2 CDMA (A1397) & must move R1205 to the R1204 place, but i'm not sure if when move the resistor , what can i do with The R1204 ????? remove it or move to R1205 PLACE?????
thanks for note about Model A1455 :+1:

**Comment by johanbalam** [comment]
Help: ipad mini after removing resistance R1204, 
itunes recognizes it as apple tv

**Comment by anieto** [comment]
Got this to work on my iPad 4 GSM A1459. MB doesn't appear to have a resistor at r1204, I simply used my fine point soldering iron placed on the spot where the r1204 should be for about a second. Did this while device was on (tip i read somewhere). Screen shut off, this is how I knew it was done. Cleaned point with alcohol.

Connected device to iTunes where it detected it as an iPhone for some reason. While connected I manually entered DFU (hold power + home for 10 seconds then release power until iTunes recognizes). In iTunes selected restore. Screen remained black until the restore was completed and device rebooted. iCloud bypassed! Thanks everyone.

**Comment by ghost** [comment]
Johan on r1205 make a short  using a pencil or solder 
and put in dfu Then restore will show ipad bro

**Comment by ghost** [comment]
Fodil remove r1204 short the r1205 if comes up as Apple TV

**Comment by fodil123** [comment]
@danocas 
ok bro i'll test tonight & inform you about result 
i'm so thankful for your help :)
My iPad is A1397 CDMA with 3G Support
best regard

**Comment by ghost** [comment]
fodil123I see it worked u posted in Twitter :)

**Comment by ghost** [comment]
breaking news managed to bypass iphone 5 icloud using this method still a lot of work first need to try in 4 4s 5s but going in the right way

**Comment by kristian467** [comment]
OMG...so it remains as an ipod?

**Comment by fodil123** [comment]
@danocas 
Yes It Worked Without Any Problem, And Thanks For Your Help :)
Btw, Explain More About The iPhone Method, i Want To Try

**Comment by ghost** [comment]
hi fodil123 the iphone 5 its on hold need jailbreak if u wan help later on wen pangu release the jailbreak for 8.0 i got pic from the process from all ipads amd the iphone maybe we try to open a blog and make more explicit were to and how to :) we be in touch bro

**Comment by fodil123** [comment]
@danocas
ok bro , i'm here to help no problem at all :)
but what's the link between jailbreak (software) and reversing GSM-module bro??
btw it's really nice to work with you :)

**Comment by pasha4ur** [comment]
=)

http://pasha4ur.org.ua/articles/difdevices/131-how-unlock-apple-ipad-2-3g-icloud-locked

https://github.com/pasha4ur/bypass-icloud-on-ipads/wiki/How-to-unlock-iCloud-locked-Apple-iPad-2,-iPad-3,-iPad-4,-iPad-Air,-iPad-mini,-iPad-mini-with-Retina-with-3G

**Comment by lucaseugenio** [comment]
Hi, this method reset the IMEI too? because the number is associated to an iCloud account, so theorically you couldn't register again. I will buy a locked one. Thanks in advice!

**Comment by lucaseugenio** [comment]
By the way, it's a iPad Mini model a1432.

**Comment by pasha4ur** [comment]
@lucaseugenio 
Only for 3G models. 

I opened topic here: https://github.com/pasha4ur/bypass-icloud-on-ipads/issues/1

**Comment by lucaseugenio** [comment]
Thank you so much! I'll try to find a 3g version. Here in Brazil they sell for a very reasonable price. :)

**Comment by lucaseugenio** [comment]
Another question: this new method doesn't work on WiFi only, or is untested?

**Comment by lucaseugenio** [comment]
Can reset lost mode?

**Comment by danocas** [comment]
reset anything icloud lost mode

**Comment by lucaseugenio** [comment]
Great! And about WiFi only? This method doesnt work at all, or is untested?

**Comment by pasha4ur** [comment]
For iphones & wifi only paid software method - around $150. 

An acquaintance through the Internet makes it. But it does not share with anyone the secret.

**Comment by nunovexia** [comment]
IPAD A1455 MM >>>what about this the R1205 was under the iron plate,,what should we do???![ipad mini a1455 layout](https://cloud.githubusercontent.com/assets/8902459/4781845/26d8d80e-5cc3-11e4-91c2-f3c1c7632c17.jpg)

**Comment by Nad4** [comment]
who needs more details check this http://myicloud.info/ help me a lot tks

**Comment by pasha4ur** [comment]
Delete this spam here. Douchi = fake

**Comment by danocas** [comment]
haha cant do pacha no moderator sorry bro but no worries :)

**Comment by danocas** [comment]
nuno u need to cut the plate dont worrie u wont see it cut :)

**Comment by nunovexia** [comment]
@danocas ....i have to cut the plate lol ??? or just scrath the plate,until the spot of r1205 appear??lol i dont understand what u mean???

**Comment by danocas** [comment]
nuno the plate that covers the resistor r1205 lol hmm ???

**Comment by danocas** [comment]
fodil just got me thinking on the wifi version off the ipads did u open any ? if yes did u found the same resistor on them ? and do they got the pinouts for the gsm module if yes last ideia reballing :)

**Comment by danocas** [comment]
look here no chip in wifi 
![ipad 2 gsm cdm wifi](https://cloud.githubusercontent.com/assets/9350743/4861089/380c44d6-60ff-11e4-82dd-229a278f0717.jpg)

**Comment by danocas** [comment]
![ipad 3g](https://cloud.githubusercontent.com/assets/9350743/4861270/f0e72182-6100-11e4-9f90-22f785f782f6.jpg)
![ipadwifi](https://cloud.githubusercontent.com/assets/9350743/4861271/f3b71b56-6100-11e4-94b0-5d000aaf653a.jpg)
see bro both got the resistor to qualcom chip

**Comment by isaactzab** [comment]
It's possible that this works with devices without modem/3g/radio chipset? I mean, changing the wifi or bluetooth chipset between devices could regenerate a new device id?

Anyone want to try?

**Comment by Mocartxx** [comment]
r1205 its regulate volts -+ when was lower its sending WC_L to MCL enable write EEPROM

**Comment by franciscoca** [comment]
can someone take a personal doubts? which resistor should I remove the ipad 4 The 1459 model?
the resistor r1204? or r1205?

**Comment by pasha4ur** [comment]
i don't provide support
06.11.2014 13:04, franciscoca пишет:

> can someone take a personal doubts? which resistor should I remove the 
> ipad 4 The 1459 model?
> the resistor r1204? or r1205?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/carcabot/iCloud-Bypass/issues/10#issuecomment-61963735.

## 

Sincerely, Pavel Churyumov

Skype: pasha4ur
ICQ: 478100248
Web: pasha4ur.org.ua

**Comment by JAckSpar0w** [comment]
hello every one, any one had tested the hardware bypass method I have one ipad 2 gsm did the hardware trick and now stuck on DFU mode with itunes error 3014 on restore to ios 8.1.1 for ipad 2 wifi model (I have test other lower ios version with the same result, change to other system installation not work too) thanks

**Comment by Mocartxx** [comment]
What resistor you remove R1205 on iPad regaled low voltage on MLC to enable access to NADA

**Comment by JAckSpar0w** [comment]
IPad 2 GSM Successful bypassed iCloud finally, Remove R1205, restor to the latest iOS 8.1.1 Wifi Model the problem was from the iTune does not have the secure link to apple de-install all security software reinstall itunes disable all resources hungry apps and remove any other USB device reboot the PC restore to 8.1.1 for wifi model and it work's

**Comment by jeanskia** [comment]
what version of iTunes used ?? i have itunes 12.0.1.26

**Comment by myicloud** [comment]
icloud all new methods 2015 http://myicloud.info/bypass-new-methods/

**Comment by shakeelwaqas** [comment]
Hello Guys .
 I try this methods and it work 10000%
Thnx

**Comment by danocas** [comment]
haaa

**Comment by yudibanjar** [comment]
A1455 Remove R1204 and jumper R1205 succes detected ipad mini wifi,,but cant restore ipad mini wifi iPad2,5_8.3_12F69_Restore.ipsw 

always stuck on "waiting for ipad"

please help....

**Comment by shakeelwaqas** [comment]
HELLOOOOO
 GUYS any one know how to bypass ipad 2/3/4/ mini wifi only not gsm wifi only 
 thnx

**Comment by olivier01** [comment]
hello 
any one have any good picture or diagram or other about the R1204 and R1205 location for an ipad A1458, this ipad don't have 3/4G only wifi
if any one can help me, 
i'm found some diagrams on internet but not realy clear to see the good position

many thanks 

olivier

**Comment by myicloud** [comment]
Did U try
http://pasha4ur.org.ua/articles/difdevices/131-how-unlock-apple-ipad-2-3g-icloud-locked

No dia domingo, 2 de agosto de 2015, olivier01 <notifications@github.com>
escreveu:

**Comment by olivier01** [comment]
hello

yes i'm found and see all this website, but there is no procedure for this ipad 4 wifi only A1458 and the R location.
the ipad that i'm have are dismounted, the processor is an A6X

if you have info, you are welkom.
i can take some photos so you have more info about this for your website to maybe help others poeple 

many thank's

Date: Sun, 2 Aug 2015 16:41:13 -0700

**Comment by myicloud** [comment]
Oki tks for help

No dia segunda-feira, 3 de agosto de 2015, olivier01 <
notifications@github.com> escreveu:

**Comment by olivier01** [comment]
Hello 

Here a picture of the iPad 4 A1458 wifi. Now the only what I need is to find the good resistor to delete..
Continue the search :-)

Mon iPhone

**Comment by shakeelwaqas** [comment]
Hello,
Any one know  about Iphone Icloud bypass  some people told me thy doing with imei number , thy just need imei to bypass any one have information about that 
Regards

**Comment by myicloud** [comment]
Yes its How GSX acconts do it, but u need one apple service GSX

No dia quarta-feira, 5 de agosto de 2015, shakeelwaqas <
notifications@github.com> escreveu:

> Hello,
> Any one know about Iphone Icloud bypass some people told me thy doing with
> imei number , thy just need imei to bypass any one have information about
> that
> Regards
>
> Sent from my iPhone
>
> > On 04 Aug 2015, at 09:35, olivier01 <notifications@github.com

**Comment by JAckSpar0w** [comment]
Hello Fellas nice to see these conversation still exist, if I'm not buttering you How to get my hand on one of those GSX Admin Account, Barrie's

**Comment by Nad4** [comment]
bypass hardware method ipad 2,3,4air mini 3g gsm only and tested
http://myicloud.info/remove-icloud-guide-for-ipad-all-3g-models/

all schems

**Comment by isaactzab** [comment]
I found a vietnam guy that claim that he has _removed successful icloud for all devices_
https://www.youtube.com/watch?v=NPou97sT2Is

**Comment by pasha4ur** [comment]
http://pasha4ur.org.ua/articles/difdevices/how-to-bypass-icloud-ipad-iphone-and-ipod

**Comment by danocas** [comment]
fuck you pasha go beg in forums for money

**Comment by pacman224** [comment]
iPad Air 2 successfully bypassed
But I lost my wifi

**Comment by badalbaidar07** [comment]
i have bypassed iPad air 2 icloud even i lost my wifi and thats fine with me atleast i can use my iPad and if i have to use internet i use Bluetooth tethering but i am still confused with the activation on icloud website. its still showing my ipad has its FMI urned ON. and i am afraid that if i have to restore again then my device will be icloud locked to with previous id? i tried to sign in with my icloud id and turned the FMI OFF and ON and OFF again but still its showing same on icloud activation website. WILL MY DEVICE BE LOCKED TO SAME ICLOUD ID THAT I HAVE FORGOTTEN AND GOT STUCKED IF I RESTORED THE DEVICE AGAIN AFTER BYPASS ????????????.........

**Comment by shakeelwaqas** [comment]
Check maybe your wifi cable is Loss 

> Shakeel Waqas | 
> BASSAP | isupport4life 
> T +27815757196
> e shakeel@isupport4life.com
>

**Comment by badalbaidar07** [comment]
its not about ipad air 2 wifi issue its fine with me with bluetooth for internet for icloud bypassed device. what i am asking is weather i can restore  my device again after i bypassed with this hardware method? because its still showing FIND MY IPHONE ON on icloud.com/activationlock. after the bypass which is in fully functioning now with hardware bypass except wifi. if i restore again i am afraid i might get icloud locked again.

**Comment by pacman224** [comment]
Yes you can 

Envoyé de mon iPhone

**Comment by badalbaidar07** [comment]
does that mean i can restore even it shows Find My iPad ON ? Even after the fully functioning ipad with this hardware bypass ipad air 2?

**Comment by pacman224** [comment]
Your ipad transformed to ipad wifi you can restore it only by firmwaire wifi 
Activation by itunes coz wifi dont work you need jailbreak to fix it 

Envoyé de mon iPhone

**Comment by badalbaidar07** [comment]
ok thanks but i tried to check Find My Ipad is turned on or not on icloud.com/activationlock. using the serial number after this bypass which worked sucessfully and its still showing My IPAD has FIND MY IPAD TURNED ON. so is it safe to restore ?

**Comment by pacman224** [comment]
Its safe , my ipad air 2 4g converted to ipad wifi and restore it with wifi firmware all fine but wifi need jailbreak to work

Envoyé de mon iPhone

**Comment by lolanana** [comment]
Indeed the recycle bin, and using Windows Explorer to look in folders; the programs you used are not designed to search for files; especially programs like Elements, which uses a catalog is not what you need now. Moving files confuses PS Elements organiser enough to make it seem like you lost files, while they're actually there. When things go wrong, use the basic tools provided in Windows itself (explorer, search).
For file recovery programs, I've use Free Iphone Manager<a href="http://www.passwordmanagers.net/Iphone-Manager.html">Free Iphone Manager</a>

 on a few occassions; it's free and it works as good as can be expected. The main thing is to stop using the external hard disk until you use this tool, and avoid writing any files to it.

**Comment by BigK22** [comment]
Hello people!!
I just tried this method on my iPad mini a1455 and can't believe it actually worked.. I'm typing this comment on the very same iPad that I unlocked iCloud for.. Fantastic method, all credit to the person who figured this out..
Anyone struggling then I can help if you ask!!!!!! 
Good luck people!!!!

**Comment by mitchellcpj** [comment]
BigK22 can u give exact location of the resistors R1205 and R1204 for A1455 MM ??

**Comment by Crap-Mayur** [comment]
did anyone tried it on ipad 6th gen coz they are checkm8 device so once cellular is removed by reistance we can change serial and mac addresses so it will unlocked
