### ISSUE TITLE
Discuss4

### ISSUE THREAD

**Issue by XeNiRoX** [carcabot/iCloud-Bypass#18]

**Comment by dekepetz** [comment]
is it any progress with bypass icloud...?

**Comment by totowa** [comment]
no progress no... only ipads from @CrokoM  open icloud 3g-wifi after resistencia metod

**Comment by ictbalie** [comment]
Perhaps these activation files can help bypass iCloud: https://t.co/T7AKeJIzqX

**Comment by Sebashock** [comment]
@TTMTT hope you are well friend

I am testing many methods but none works :(

**Comment by charleszero** [comment]
i´m too, my 4s with 8.1.1 12b435 in initial active window, test various methods with server but not work. i´m look for this today.
